version: '3'

services:
    api_server:
        container_name: api_server
        image: api_server 
        volumes:
            - .:/app/
        ports:
            - "8080:3020"
        command: [ "npm", "run",  "dev", "--", "src/${ENTRY}" ]
